batch_list: "0-batch_list.txt"
fname_dir_path: "1-HQ-661k-collection/fnames_lists" 
index_type: "roaring"           #Set either "sdsl-hybrid" or "roaring"
n_threads: 8
d: 20                         
m: 50                         